// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4RpC44k8zKw3IORRCkmg-QsbE4jOGcCI',
    appId: '1:1013626246346:web:5b7f3f1399cb91bbc45033',
    messagingSenderId: '1013626246346',
    projectId: 'iot-41c94',
    authDomain: 'iot-41c94.firebaseapp.com',
    databaseURL: 'https://iot-41c94-default-rtdb.firebaseio.com',
    storageBucket: 'iot-41c94.firebasestorage.app',
    measurementId: 'G-QG7RE4VRX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0uONciv_bZFnL_50w-eWZV6k5ZVdJEQ8',
    appId: '1:1013626246346:android:7e069a7381377fbdc45033',
    messagingSenderId: '1013626246346',
    projectId: 'iot-41c94',
    databaseURL: 'https://iot-41c94-default-rtdb.firebaseio.com',
    storageBucket: 'iot-41c94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALhGjFU7PTetg8OEy6b-FWGc9yom_3sEY',
    appId: '1:1013626246346:ios:8115e08ae9d4ae7bc45033',
    messagingSenderId: '1013626246346',
    projectId: 'iot-41c94',
    databaseURL: 'https://iot-41c94-default-rtdb.firebaseio.com',
    storageBucket: 'iot-41c94.firebasestorage.app',
    iosBundleId: 'com.example.flutterwavepaymenttesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALhGjFU7PTetg8OEy6b-FWGc9yom_3sEY',
    appId: '1:1013626246346:ios:8115e08ae9d4ae7bc45033',
    messagingSenderId: '1013626246346',
    projectId: 'iot-41c94',
    databaseURL: 'https://iot-41c94-default-rtdb.firebaseio.com',
    storageBucket: 'iot-41c94.firebasestorage.app',
    iosBundleId: 'com.example.flutterwavepaymenttesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRIfHLn5-WFnELWQNTdKqxYHAPFq8YxAA',
    appId: '1:1013626246346:web:4b6a4f42b92b1cb5c45033',
    messagingSenderId: '1013626246346',
    projectId: 'iot-41c94',
    authDomain: 'iot-41c94.firebaseapp.com',
    databaseURL: 'https://iot-41c94-default-rtdb.firebaseio.com',
    storageBucket: 'iot-41c94.firebasestorage.app',
    measurementId: 'G-8VXJWH13CG',
  );
}
